version: "3.9"

services:
  djangoapp:
    container_name: djangoapp
    build:
      context: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend/djangoapp:/djangoapp
      - ./backend/data/web/static:/data/web/static/
      - ./backend/data/web/media:/data/web/media/
    env_file:
      - ./backend/dotenv_files/.env
    depends_on:
      - psql
  psql:
    container_name: psql
    image: postgres:13-alpine
    volumes:
      - ./backend/data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./backend/dotenv_files/.env
